[package]
name = "arrow2"
version = "0.1.0"
authors = ["Jorge C. Leitao <jorgecarleitao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
rand = "0.7"
num = "0.3"
chrono = "0.4"

csv = { version = "1.1", optional = true }
regex = { version = "1.3", optional = true }
lazy_static = { version = "1.4", optional = true }
lexical-core = { version = "^0.7", optional = true }

[dev-dependencies]
criterion = "0.3"
tempfile = "3"

[features]
default = ["io_csv"]
io_csv = ["csv", "lazy_static", "lexical-core", "regex"]

[[bench]]
name = "take_kernels"
harness = false
