[package]
name = "arrow2"
version = "0.1.0"
authors = ["All Apache Arrow contributors", "Jorge C. Leitao <jorgecarleitao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
chrono = "0.4"
# We need to Hash values before sending them to an hasher. This
# crate provides HashMap that assumes pre-hashed values.
hash_hasher = "2.0.3"

csv = { version = "1.1", optional = true }
regex = { version = "1.3", optional = true }
lazy_static = { version = "1.4", optional = true }
lexical-core = { version = "^0.7", optional = true }

serde = { version = "1.0", features = ["rc"], optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", features = ["preserve_order"], optional = true }
indexmap = { version = "1.6", optional = true }

flatbuffers = { version = "^0.8", optional = true }
hex = { version = "0.4", optional = true }

[dev-dependencies]
rand = "0.7"
criterion = "0.3"
tempfile = "3"
flate2 = "1"
doc-comment = "0.3"

[features]
default = ["io_csv", "io_json", "io_ipc", "io_json_integration", "regex"]
io_csv = ["csv", "lazy_static", "lexical-core", "regex"]
io_json = ["serde", "serde_derive", "serde_json", "indexmap"]
io_ipc = ["flatbuffers"]
io_json_integration = ["io_json", "hex"]

[[bench]]
name = "take_kernels"
harness = false
