name: Check and test

on: [push, pull_request]

jobs:
  # build the library, a compilation step used by multiple steps below
  linux-build-lib:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
      - &cache-cargo
        name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: /github/home/.cargo
          # these represent dependencies downloaded by cargo
          # and thus do not depend on the OS, arch nor rust version.
          key: cargo-cache-
      - &cache-target
        name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /github/home/target
          # these represent compiled steps of both dependencies and arrow
          # and thus are specific for a particular OS, arch and rust version.
          key: ${{ runner.os }}-amd64-target-cache-stable
      - &default-toolchain
        name: Setup toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add rustfmt
      - name: Build
        run: |
          export CARGO_HOME="/github/home/.cargo"
          export CARGO_TARGET_DIR="/github/home/target"
          cargo build

  # test the crate
  linux-test:
    name: Test
    needs: [linux-build-lib]
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - *cache-cargo
      - *cache-target
      - *default-toolchain
      - name: Run
        run: |
          export CARGO_HOME="/github/home/.cargo"
          export CARGO_TARGET_DIR="/github/home/target"
          cargo test

  windows-and-macos:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # TODO: this won't cache anything, which is expensive. Setup this action
      # with a OS-dependent path.
      - *default-toolchain
      - name: Run
        shell: bash
        run: cargo test

  clippy:
    name: Clippy
    needs: [linux-build-lib]
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - *cache-cargo
      - *cache-target
      - name: Setup toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add rustfmt clippy
      - name: Run
        run: |
          export CARGO_HOME="/github/home/.cargo"
          export CARGO_TARGET_DIR="/github/home/target"
          cargo clippy

  miri-checks:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup toolchain
        run: |
          rustup toolchain install nightly-2021-01-19
          rustup default nightly-2021-01-19
          rustup component add rustfmt miri
      - name: Run Miri Checks
        env:
          RUST_BACKTRACE: full
          RUST_LOG: 'trace'
        run: |
          export MIRIFLAGS="-Zmiri-disable-isolation"
          cargo miri setup
          cargo clean
          cargo miri test || true

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: /home/runner/.cargo
          # this key is not equal because the user is different than on a container (runner vs github)
          key: cargo-coverage-cache-
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/target
          # this key is not equal because coverage uses different compilation flags.
          key: ${{ runner.os }}-amd64-target-coverage-cache-stable-
      - name: Run coverage
        run: |
          export CARGO_HOME="/home/runner/.cargo"
          export CARGO_TARGET_DIR="/home/runner/target"

          # 2020-11-15: There is a cargo-tarpaulin regression in 0.17.0
          # see https://github.com/xd009642/tarpaulin/issues/618
          cargo install --version 0.16.0 cargo-tarpaulin
          cargo tarpaulin --out Xml
      - name: Report coverage
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash)

  feature-compilation:
    name: Feature coverage
    needs: [linux-build-lib]
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
      - *cache-cargo
      - *cache-target
      - name: Setup toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add rustfmt clippy
          cargo install cargo-all-features
      - name: Run clippy
        run: |
          export CARGO_HOME="/github/home/.cargo"
          export CARGO_TARGET_DIR="/github/home/target"
          cargo clippy

  # test the arrow crate builds against wasm32 in stable rust
  wasm32-build:
    name: wasm32 build
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - *cache-cargo
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /github/home/target
          key: ${{ runner.os }}-amd64-target-wasm32-cache-nightly-2020-11-24
      - name: Setup toolchain
        run: |
          rustup toolchain install nightly-2020-11-24
          rustup override set nightly-2020-11-24
          rustup component add rustfmt
          rustup target add wasm32-unknown-unknown
      - name: Build arrow crate
        run: |
          export CARGO_HOME="/github/home/.cargo"
          export CARGO_TARGET_DIR="/github/home/target"
          cargo build --target wasm32-unknown-unknown
